
accounts:
  # Filename of GnuCash accounts
  kind: piecash
  file: example2.gnucash

report: //import report/esef/esef.yaml
#report: //import report/esef/esef-fr.yaml

#pretty-print: true

metadata: //import metadata-esef.yaml

